// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBioh0R6Xyt8tilXoHMZSum2PF37HS3p2Y',
    appId: '1:639744588575:web:c9524b6bf2e593b9914e2a',
    messagingSenderId: '639744588575',
    projectId: 'login-signup-70864',
    authDomain: 'login-signup-70864.firebaseapp.com',
    storageBucket: 'login-signup-70864.firebasestorage.app',
    measurementId: 'G-2KBKH6ECE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHG3uMJAe2BNF5envD6BOPF8gqM-Z3_o',
    appId: '1:639744588575:android:90d07fd385611791914e2a',
    messagingSenderId: '639744588575',
    projectId: 'login-signup-70864',
    storageBucket: 'login-signup-70864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnedXhRo0t5aSCqf_8N4K8CF8iT6-NlU',
    appId: '1:639744588575:ios:5d2e53f9991768af914e2a',
    messagingSenderId: '639744588575',
    projectId: 'login-signup-70864',
    storageBucket: 'login-signup-70864.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnedXhRo0t5aSCqf_8N4K8CF8iT6-NlU',
    appId: '1:639744588575:ios:5d2e53f9991768af914e2a',
    messagingSenderId: '639744588575',
    projectId: 'login-signup-70864',
    storageBucket: 'login-signup-70864.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBioh0R6Xyt8tilXoHMZSum2PF37HS3p2Y',
    appId: '1:639744588575:web:2e510371b2c2e223914e2a',
    messagingSenderId: '639744588575',
    projectId: 'login-signup-70864',
    authDomain: 'login-signup-70864.firebaseapp.com',
    storageBucket: 'login-signup-70864.firebasestorage.app',
    measurementId: 'G-403X2TJNJ8',
  );
}
